- Fix `AttributeError: module 'pyranges' has no attribute 'from_dfs'` causing to_ranges function to return a pandas Dataframe instead of PyRanges object (#9) - Logging exception in case the to_ranges function fails at creating the pr.PyRanges object - adding Exception (PEP 8: E722)